/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_CONN curHTTP;
extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_led(WORD);
void HTTPPrint_btn(WORD);
void HTTPPrint_pot(WORD);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
        case 0x00000000:
			HTTPPrint_led(0);
			break;
        case 0x00000001:
			HTTPPrint_led(1);
			break;
        case 0x00000002:
			HTTPPrint_led(2);
			break;
        case 0x00000003:
			HTTPPrint_led(3);
			break;
        case 0x00000004:
			HTTPPrint_led(4);
			break;
        case 0x00000005:
			HTTPPrint_btn(0);
			break;
        case 0x00000006:
			HTTPPrint_btn(1);
			break;
        case 0x00000007:
			HTTPPrint_btn(2);
			break;
        case 0x00000008:
			HTTPPrint_btn(3);
			break;
        case 0x00000009:
			HTTPPrint_btn(4);
			break;
        case 0x0000000a:
			HTTPPrint_pot(0);
			break;
        case 0x0000000b:
			HTTPPrint_pot(1);
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
